Ticket 505: fix error in standard odoo when no planned start date is set for MO
Fix error below:
 File "/home/odoo/src/odoo/addons/mrp/models/mrp_production.py", line 456, in _onchange_date_planned_start
    self.date_planned_finished = self.date_planned_start + datetime.timedelta(hours=1)
TypeError: unsupported operand type(s) for +: 'bool' and 'datetime.timedelta'